## Exercise1.6

In [1]:
import numpy as np

In [2]:
class FormalNeuronLayer:
    def __init__(self, w, h):
        self.w = w
        self.h = h

    def forward(self, x):
        p = np.dot(self.w, x)
        y = p > self.h
        return y.astype(np.int)


x = np.array([[1, 1, 1],
              [0, 1, 0],
              [1, 0, 0],
              [0, 0, 1]])

w = np.array([[3, 2, 2, 0],
              [4, 1, 5, 2],
              [1, 0, 1, 4],
              [0, 1, 0, 1]])

h = np.array([[2],
              [6],
              [1],
              [0]])

u = np.array([[4, 1, 4, 3],
              [2, 3, 0, 1],
              [0, 1, 2, 4],
              [3, 1, 1, 2]])

g = np.array([[1],
              [4],
              [3],
              [5]])

formalNeuron1 = FormalNeuronLayer(w,h)
formalNeuron2 = FormalNeuronLayer(u,g)

y = formalNeuron1.forward(x)
print(y)

z = formalNeuron2.forward(y)
print(z)

[[1 1 1]
 [1 0 0]
 [1 0 1]
 [0 1 1]]
[[1 1 1]
 [1 0 0]
 [0 1 1]
 [0 0 1]]


In [4]:
np.dot(w, x)

array([[5, 5, 3],
       [9, 5, 6],
       [2, 1, 5],
       [0, 1, 1]])

In [5]:
np.dot(u, y)

array([[ 9,  7, 11],
       [ 5,  3,  3],
       [ 3,  4,  6],
       [ 5,  5,  6]])